### ISSUE TITLE
Update Enrollment side context on hover; properly label axes

### ISSUE THREAD

**Issue by octo-berkeleytime** [asuc-octo/berkeleytime#198]
<strong>Email address</strong>
yuancheng.tsai@berkeley.edu

<strong>Please briefly describe the bug.</strong>
Not a bug, but a feature: would like to see all class information listed on the right side on the enrollment page (instead of the class I'm hovering over)

<strong>What kind of bug is it?</strong>
Enrollment Data is not appearing

<strong>Which page is the problem on?</strong>
Enrollment

<strong>What browser/system is this happening on?</strong>
Safari

<strong>What class/schedule is having the issue? (BIO 1A, CS 61A etc.)</strong>
In my example, I have CS61A/B

<strong>If you can, upload a screen shot of the bug.</strong>
1zok9v9xuJ8Dcs_bbptkTBMv-yR8bgb0E

<strong>If our categories didn't quite fit the description of your bug, please tell us how to replicate the issue in as much detail as you can.</strong>

**Comment by mathhulk** [comment]
- [ ]  Properly label the axes for Enrollment and Grades tabs
- [ ]  Clean up tooltip design for Enrollment and Grades tabs to improve readability
- [ ]  Update Enrollment side context when hovering _near_ a line

**Comment by xyntechx** [comment]
Hi @mathhulk :) Could I clarify on the task items please?

### Properly label the axes for Enrollment and Grades tabs

Meaning indicate that the vert axis is percentage of students (for grades) or class filled (for enrollment), and hoz axis as number of days after start of enrollment (for enrollment)?

### Clean up tooltip design for Enrollment and Grades tabs to improve readability

![Image](https://github.com/asuc-octo/berkeleytime/assets/61340875/0e2128c5-56e5-4a31-b4f2-3d617ee98dbb)

Assuming the circled element is the tooltip, should we make it so that it just shows the class name and enrollment percentage? Since the classes are all color-coded, even when 2 classes have the same name but with different instructors, the user can still identify which class has which instructor by associating the colors.

### Update Enrollment side context when hovering near a line

This bugfix is only for the scenario when the user has selected more than one class right? And are we still just going to show just one class at a time in the side context, depending on which line is being hovered on?

**Comment by xyntechx** [comment]
@mathhulk bump ^^ :)))

**Comment by xyntechx** [comment]
CC @Jdyn and @kevinzwang

**Comment by Jdyn** [comment]
Hey all of your assumptions and questions are correct 👌
